// public-good-design-system-react-headless/components/CalendarTableData.tsx
// CalendarTableData component
//
// A single day cell within a CalendarTable grid. Renders as a <td> with
// role="gridcell", supporting selected and today states for visual and
// accessible indication. Uses a roving tabindex pattern where the selected
// cell receives focus. Designed for use inside a CalendarTableRow.
//
// Props:
//   className — string, optional. CSS class name.
//   selected — boolean, default false. Whether this day cell is selected.
//   today — boolean, default false. Whether this day cell represents today's date.
//   children — ReactNode, required. Day content, typically the day number.
//   ...restProps — additional HTML attributes spread onto the <td>.
//
// Syntax:
//   <CalendarTableData>15</CalendarTableData>
//
// Examples:
//   
//   <CalendarTableData selected today>15</CalendarTableData>
//
//   
//   <CalendarTableData>22</CalendarTableData>
//
// Keyboard:
//   - Tab: Focus moves to the selected cell (tabindex="0")
//   - Arrow keys: Typically handled by the parent CalendarTable grid navigation
//
// Accessibility:
//   - role="gridcell" identifies the cell as part of a grid
//   - aria-selected set to true when selected; omitted otherwise
//   - aria-current="date" set when the cell represents today; omitted otherwise
//   - Roving tabindex: tabindex="0" when selected, "-1" otherwise
//
// Internationalization:
//   - Day content comes through children prop; no hardcoded strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Must be used inside a CalendarTableRow
//
// References:
//   - WAI-ARIA Grid Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/grid/

import React from "react";

export interface CalendarTableDataProps {
    className?: string;
    /** Whether this day is selected. */
    selected?: boolean;
    /** Whether this day is today. */
    today?: boolean;
    /** Day content. */
    children: React.ReactNode;
    [key: string]: unknown;
}

export default function CalendarTableData({
    className = "",
    selected = false,
    today = false,
    children,
    ...restProps
}: CalendarTableDataProps) {
    return (
        <td
        className={`calendar-table-data ${className}`}
        role="gridcell"
        aria-selected={selected || undefined}
        aria-current={today ? "date" : undefined}
        tabIndex={selected ? 0 : -1}
        {...restProps}
        >
        {children}
        </td>
    );
}

// public-good-design-system-vue-headless/components/CalendarTableData.vue
<script setup lang="ts">

    // CalendarTableData component
    //
    // A single day cell within a CalendarTable grid. Renders as a <td> with
    // role="gridcell", supporting selected and today states for visual and
    // accessible indication. Uses a roving tabindex pattern where the selected
    // cell receives focus. Designed for use inside a CalendarTableRow.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   selected — boolean, default false. Whether this day cell is selected.
    //   today — boolean, default false. Whether this day cell represents today's date.
    //   default slot. Day content, typically the day number.
    //   ...restProps — additional HTML attributes spread onto the <td>.
    //
    // Syntax:
    //   <CalendarTableData>15</CalendarTableData>
    //
    // Examples:
    //   <!-- Selected day that is also today -->
    //   <CalendarTableData selected today>15</CalendarTableData>
    //
    //   <!-- Regular unselected day -->
    //   <CalendarTableData>22</CalendarTableData>
    //
    // Keyboard:
    //   - Tab: Focus moves to the selected cell (tabindex="0")
    //   - Arrow keys: Typically handled by the parent CalendarTable grid navigation
    //
    // Accessibility:
    //   - role="gridcell" identifies the cell as part of a grid
    //   - aria-selected set to true when selected; omitted otherwise
    //   - aria-current="date" set when the cell represents today; omitted otherwise
    //   - Roving tabindex: tabindex="0" when selected, "-1" otherwise
    //
    // Internationalization:
    //   - Day content comes through default slot; no hardcoded strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Must be used inside a CalendarTableRow
    //
    // References:
    //   - WAI-ARIA Grid Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/grid/

    withDefaults(defineProps<{
        /** Whether this day is selected. */
        selected?: boolean;
        /** Whether this day is today. */
        today?: boolean;
    }>(), {
        selected: false,
        today: false,
    });

</script>

<template>
    <!-- CalendarTableData.vue -->
    <td
        class="calendar-table-data"
        role="gridcell"
        :aria-selected="selected || undefined"
        :aria-current="today ? 'date' : undefined"
        :tabindex="selected ? 0 : -1"
    >
        <slot />
    </td>
</template>
