// public-good-design-system-react-headless/components/DataTableData.tsx
// DataTableData component
//
// A single data cell within a DataTableRow. Renders as a <td> with
// role="gridcell". Supports an active state for indicating the currently
// focused or selected cell, communicated via aria-selected for screen
// readers. Uses a roving tabindex pattern.
//
// Props:
//   className — string, optional. CSS class name.
//   active — boolean, default false. Whether this cell is active/selected.
//   children — ReactNode, required. Cell content.
//   ...restProps — additional HTML attributes spread onto the <td>.
//
// Syntax:
//   <DataTableData>Alice</DataTableData>
//   <DataTableData active>Bob</DataTableData>
//
// Keyboard:
//   None built-in — keyboard navigation handled at the DataTable grid level.
//
// Accessibility:
//   - role="gridcell" identifies the cell as part of an interactive grid
//   - aria-selected set to true when active; omitted otherwise
//   - Roving tabindex: tabindex="0" when active, "-1" otherwise
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Must be used inside a DataTableRow
//
// References:
//   - WAI-ARIA Grid Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/grid/

import React from "react";

export interface DataTableDataProps {
    className?: string;
    /** Whether this cell is active/selected. */
    active?: boolean;
    /** Cell content. */
    children: React.ReactNode;
    [key: string]: unknown;
}

export default function DataTableData({
    className = "",
    active = false,
    children,
    ...restProps
}: DataTableDataProps) {
    return (
        <td
        className={`data-table-data ${className}`}
        role="gridcell"
        aria-selected={active || undefined}
        tabIndex={active ? 0 : -1}
        {...restProps}
        >
        {children}
        </td>
    );
}

// public-good-design-system-vue-headless/components/DataTableData.vue
<script setup lang="ts">

    // DataTableData component
    //
    // A single data cell within a DataTableRow. Renders as a <td> with
    // role="gridcell". Supports an active state for indicating the currently
    // focused or selected cell, communicated via aria-selected for screen
    // readers. Uses a roving tabindex pattern.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   active — boolean, default false. Whether this cell is active/selected.
    //   default slot. Cell content.
    //   ...restProps — additional HTML attributes spread onto the <td>.
    //
    // Syntax:
    //   <DataTableData>Alice</DataTableData>
    //   <DataTableData active>Bob</DataTableData>
    //
    // Keyboard:
    //   None built-in — keyboard navigation handled at the DataTable grid level.
    //
    // Accessibility:
    //   - role="gridcell" identifies the cell as part of an interactive grid
    //   - aria-selected set to true when active; omitted otherwise
    //   - Roving tabindex: tabindex="0" when active, "-1" otherwise
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Must be used inside a DataTableRow
    //
    // References:
    //   - WAI-ARIA Grid Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/grid/

    withDefaults(defineProps<{
        /** Whether this cell is active/selected. */
        active?: boolean;
    }>(), {
        active: false,
    });

</script>

<template>
    <!-- DataTableData.vue -->
    <td
        class="data-table-data"
        role="gridcell"
        :aria-selected="active || undefined"
        :tabindex="active ? 0 : -1"
    >
        <slot />
    </td>
</template>
