// public-good-design-system-svelte-headless/components/GrailLayoutLeftAside.svelte
<script lang="ts">
    // GrailLayoutLeftAside component
    //
    // A headless container for the left aside section of a GrailLayout. It
    // typically contains navigation menus, filters, or supplementary content.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   children — Snippet, required. Content to render inside the left aside.
    //   ...restProps — additional HTML attributes spread onto the <div>.
    //
    // Syntax:
    //   <GrailLayoutLeftAside>{children}</GrailLayoutLeftAside>
    //
    // Examples:
    //   <GrailLayoutLeftAside><nav>Navigation menu</nav></GrailLayoutLeftAside>
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling

    import type { Snippet } from "svelte";

    let {
        class: className = "",
        children,
        ...restProps
    }: {
        children: Snippet;
        [key: string]: unknown;
    } = $props();
</script>

<!-- GrailLayoutLeftAside.svelte -->
<div class={`grail-layout-left-aside ${className}`} {...restProps}>
    {@render children()}
</div>

// public-good-design-system-vue-headless/components/GrailLayoutLeftAside.vue
<script setup lang="ts">

    // GrailLayoutLeftAside component
    //
    // A headless container for the left aside section of a GrailLayout.
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling

</script>

<template>
    <!-- GrailLayoutLeftAside.vue -->
    <div class="grail-layout-left-aside">
        <slot />
    </div>
</template>
