// public-good-design-system-react-headless/components/NavigationMenu.tsx
// NavigationMenu component
//
// A headless navigation menu that provides a semantic <nav> landmark with an
// accessible label for site-wide or section-level navigation. It enables screen
// reader users to quickly locate and jump to the navigation area using landmark
// navigation. Suitable for primary navigation bars, sidebar navigation, footer
// navigation, and any grouped set of navigation links.
//
// Props:
//   className — string, optional. CSS class name.
//   label — string, required. Accessible name via aria-label to distinguish this nav landmark.
//   children — ReactNode, required. Navigation content (links, lists, nested menus).
//   ...restProps — additional HTML attributes spread onto the <nav>.
//
// Syntax:
//   <NavigationMenu label="Main navigation">
//     <a href="/">Home</a>
//   </NavigationMenu>
//
// Examples:
//   
//   <NavigationMenu label="Main navigation">
//     <a href="/">Home</a>
//     <a href="/about">About</a>
//   </NavigationMenu>
//
//   
//   <NavigationMenu label="Footer navigation">
//     <ul>
//       <li><a href="/privacy">Privacy Policy</a></li>
//       <li><a href="/terms">Terms of Service</a></li>
//     </ul>
//   </NavigationMenu>
//
// Keyboard:
//   - None — this is a passive container. Navigation links inside use standard
//     Tab key focus and Enter/Space activation provided by the browser.
//
// Accessibility:
//   - <nav> element implicitly has role="navigation", making it a navigation landmark
//   - aria-label distinguishes this navigation from other <nav> landmarks on the page
//
// Internationalization:
//   - The label prop accepts any translated string
//   - All navigation content comes through the children prop
//   - No hardcoded user-facing strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - No internal state or keyboard handling; relies on native link behavior
//
// References:
//   - WAI-ARIA Navigation Landmark: https://www.w3.org/TR/wai-aria-1.2/#navigation
//   - WAI-ARIA Landmarks: https://www.w3.org/WAI/ARIA/apd/practices/landmark-regions/

import React from "react";

export interface NavigationMenuProps {
    className?: string;
    /** Accessible label. */
    label: string;
    /** Navigation content. */
    children: React.ReactNode;
    [key: string]: unknown;
}

export default function NavigationMenu({
    className = "",
    label,
    children,
    ...restProps
}: NavigationMenuProps) {
    return (
        <nav
        className={`navigation-menu ${className}`}
        aria-label={label}
        {...restProps}
        >
        {children}
        </nav>
    );
}

// public-good-design-system-vue-headless/components/NavigationMenu.vue
<script setup lang="ts">

    // NavigationMenu component
    //
    // A headless navigation menu that provides a semantic <nav> landmark with an
    // accessible label for site-wide or section-level navigation. It enables screen
    // reader users to quickly locate and jump to the navigation area using landmark
    // navigation. Suitable for primary navigation bars, sidebar navigation, footer
    // navigation, and any grouped set of navigation links.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   label — string, required. Accessible name via aria-label to distinguish this nav landmark.
    //   default slot. Navigation content (links, lists, nested menus).
    //   ...restProps — additional HTML attributes spread onto the <nav>.
    //
    // Syntax:
    //   <NavigationMenu label="Main navigation">
    //     <a href="/">Home</a>
    //   </NavigationMenu>
    //
    // Examples:
    //   <!-- Primary navigation -->
    //   <NavigationMenu label="Main navigation">
    //     <a href="/">Home</a>
    //     <a href="/about">About</a>
    //   </NavigationMenu>
    //
    //   <!-- Footer navigation with list structure -->
    //   <NavigationMenu label="Footer navigation">
    //     <ul>
    //       <li><a href="/privacy">Privacy Policy</a></li>
    //       <li><a href="/terms">Terms of Service</a></li>
    //     </ul>
    //   </NavigationMenu>
    //
    // Keyboard:
    //   - None — this is a passive container. Navigation links inside use standard
    //     Tab key focus and Enter/Space activation provided by the browser.
    //
    // Accessibility:
    //   - <nav> element implicitly has role="navigation", making it a navigation landmark
    //   - aria-label distinguishes this navigation from other <nav> landmarks on the page
    //
    // Internationalization:
    //   - The label prop accepts any translated string
    //   - All navigation content comes through the default slot
    //   - No hardcoded user-facing strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - No internal state or keyboard handling; relies on native link behavior
    //
    // References:
    //   - WAI-ARIA Navigation Landmark: https://www.w3.org/TR/wai-aria-1.2/#navigation
    //   - WAI-ARIA Landmarks: https://www.w3.org/WAI/ARIA/apd/practices/landmark-regions/

    defineProps<{
        /** Accessible label. */
        label: string;
    }>();

</script>

<template>
    <!-- NavigationMenu.vue -->
    <nav
        class="navigation-menu"
        :aria-label="label"
    >
        <slot />
    </nav>
</template>
