// public-good-design-system-react-headless/components/TreeNavList.tsx
// TreeNavList component
//
// A headless hierarchical list using the ARIA tree role with full keyboard
// navigation. Renders a <ul> with role="tree" and manages focus movement
// between tree items using ArrowDown/ArrowUp with wrapping, plus Home/End
// to jump to first/last items. Commonly used for file browsers, organizational
// charts, nested data displays, or any hierarchical structure.
//
// Props:
//   className — string, optional. CSS class name.
//   label — string, required. Accessible name for the tree via aria-label.
//   children — ReactNode, required. Tree item elements with role="treeitem".
//   ...restProps — additional HTML attributes spread onto the <ul>.
//
// Syntax:
//   <TreeNavList label="File browser">...</TreeNavList>
//
// Examples:
//   
//   <TreeNavList label="File browser">
//     <li role="treeitem" tabindex="0">Documents</li>
//     <li role="treeitem" tabindex="-1">Photos</li>
//     <li role="treeitem" tabindex="-1">Videos</li>
//   </TreeNavList>
//
// Keyboard:
//   - ArrowDown: move focus to the next tree item (wraps to first)
//   - ArrowUp: move focus to the previous tree item (wraps to last)
//   - Home: move focus to the first tree item
//   - End: move focus to the last tree item
//
// Accessibility:
//   - role="tree" identifies the container as a tree widget for hierarchical data
//   - aria-label={label} provides an accessible name describing the tree
//
// Internationalization:
//   - The label prop accepts any translated string
//   - No hardcoded user-facing strings
//
// Claude rules:
//   - Headless: no CSS, no styles -- consumer provides all styling
//   - Queries [role='treeitem'] descendants for keyboard navigation
//   - Uses useState() for internal DOM reference
//
// References:
//   - WAI-ARIA Tree View Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/TreeNavList/
//   - WAI-ARIA tree role: https://www.w3.org/TR/wai-aria-1.2/#tree

import React, { useRef } from "react";

export interface TreeNavListProps {
    className?: string;
    /** Accessible label. */
    label: string;
    /** Tree item elements. */
    children: React.ReactNode;
    [key: string]: unknown;
}

export default function TreeNavList({
    className = "",
    label,
    children,
    ...restProps
}: TreeNavListProps) {
    const treeRef = useRef<HTMLElement>(null);

    function handleKeyDown(event: React.KeyboardEvent) {
        if (!treeRef.current) return;
        const items = Array.from(
            treeRef.current.querySelectorAll<HTMLElement>("[role='treeitem']"),
        );
        const current = document.activeElement as HTMLElement;
        const index = items.indexOf(current);
        switch (event.key) {
            case "ArrowDown": {
                event.preventDefault();
                const next = index < items.length - 1 ? index + 1 : 0;
                items[next]?.focus();
                break;
            }
            case "ArrowUp": {
                event.preventDefault();
                const prev = index > 0 ? index - 1 : items.length - 1;
                items[prev]?.focus();
                break;
            }
            case "Home": {
                event.preventDefault();
                items[0]?.focus();
                break;
            }
            case "End": {
                event.preventDefault();
                items[items.length - 1]?.focus();
                break;
            }
        }
    }

    return (
        <ol
        className={`tree-nav-list ${className}`}
        role="tree"
        aria-label={label}
        ref={treeRef}
        onKeyDown={handleKeyDown}
        {...restProps}
        >
        {children}
        </ol>
    );
}

// public-good-design-system-vue-headless/components/TreeNavList.vue
<script setup lang="ts">

    // TreeNavList component
    //
    // A headless hierarchical list using the ARIA tree role with full keyboard
    // navigation. Renders a <ul> with role="tree" and manages focus movement
    // between tree items using ArrowDown/ArrowUp with wrapping, plus Home/End
    // to jump to first/last items. Commonly used for file browsers, organizational
    // charts, nested data displays, or any hierarchical structure.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   label — string, required. Accessible name for the tree via aria-label.
    //   default slot. Tree item elements with role="treeitem".
    //   ...restProps — additional HTML attributes spread onto the <ul>.
    //
    // Syntax:
    //   <TreeNavList label="File browser">...</TreeNavList>
    //
    // Examples:
    //   <!-- File browser tree view -->
    //   <TreeNavList label="File browser">
    //     <li role="treeitem" tabindex="0">Documents</li>
    //     <li role="treeitem" tabindex="-1">Photos</li>
    //     <li role="treeitem" tabindex="-1">Videos</li>
    //   </TreeNavList>
    //
    // Keyboard:
    //   - ArrowDown: move focus to the next tree item (wraps to first)
    //   - ArrowUp: move focus to the previous tree item (wraps to last)
    //   - Home: move focus to the first tree item
    //   - End: move focus to the last tree item
    //
    // Accessibility:
    //   - role="tree" identifies the container as a tree widget for hierarchical data
    //   - aria-label={label} provides an accessible name describing the tree
    //
    // Internationalization:
    //   - The label prop accepts any translated string
    //   - No hardcoded user-facing strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles -- consumer provides all styling
    //   - Queries [role='treeitem'] descendants for keyboard navigation
    //   - Uses ref() for internal DOM reference
    //
    // References:
    //   - WAI-ARIA Tree View Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/TreeNavList/
    //   - WAI-ARIA tree role: https://www.w3.org/TR/wai-aria-1.2/#tree

    import { ref } from "vue";

    const props = defineProps<{
        /** Accessible label. */
        label: string;
    }>();

    const treeRef = ref<HTMLElement | undefined>(undefined);

    function onkeydown(event: KeyboardEvent) {
        if (!treeRef.value) return;
        const items = Array.from(
            treeRef.value.querySelectorAll<HTMLElement>("[role='treeitem']"),
        );
        const current = document.activeElement as HTMLElement;
        const index = items.indexOf(current);
        switch (event.key) {
            case "ArrowDown": {
                event.preventDefault();
                const next = index < items.length - 1 ? index + 1 : 0;
                items[next]?.focus();
                break;
            }
            case "ArrowUp": {
                event.preventDefault();
                const prev = index > 0 ? index - 1 : items.length - 1;
                items[prev]?.focus();
                break;
            }
            case "Home": {
                event.preventDefault();
                items[0]?.focus();
                break;
            }
            case "End": {
                event.preventDefault();
                items[items.length - 1]?.focus();
                break;
            }
        }
    }

</script>

<template>
    <!-- TreeNavList.vue -->
    <ol
        class="tree-nav-list"
        role="tree"
        :aria-label="label"
        ref="treeRef"
        @keydown="onkeydown"
    >
        <slot />
    </ol>
</template>
