// public-good-design-system-react-headless/components/VitalSignHeightCmView.tsx
// VitalSignHeightCmView component
//
// A read-only display of a height value in centimeters (cm). This
// component renders the numeric value as text content inside a span element with
// appropriate ARIA attributes for accessibility. It is the display-only companion
// to VitalSignHeightCmInput, used for showing height
// readings in patient dashboards, medical records, and health monitoring displays.
//
// Props:
//   className — string, optional. CSS class name.
//   value — number, required. Height value in centimeters.
//   label — string, required. Accessible description via aria-label (e.g., "175 cm height").
//   ...restProps — additional HTML attributes spread onto the outer span.
//
// Syntax:
//   <VitalSignHeightCmView value={175} label="175 cm height" />
//
// Examples:
//
//   <VitalSignHeightCmView value={175} label="175 cm height" />
//
//
//   <VitalSignHeightCmView value={160} label="160 cm height" />
//
// Keyboard:
//   - None — this is a passive, read-only display element
//
// Accessibility:
//   - role="img" on the outer span indicates it represents a visual/graphic element
//   - aria-label provides the full height description for screen readers
//   - data-value attribute enables consumer CSS styling based on the value
//
// Internationalization:
//   - The label prop allows localized height descriptions
//   - No hardcoded user-facing strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Companion to VitalSignHeightCmInput for the Input/View pattern
//
// References:
//   - WAI-ARIA img role: https://www.w3.org/WAI/ARIA/apd/roles/img/

import React from "react";

export interface VitalSignHeightCmViewProps {
    className?: string;
    /** Height value in centimeters. */
    value: number;
    /** Accessible description. */
    label: string;
    [key: string]: unknown;
}

export default function VitalSignHeightCmView({
    className = "",
    value,
    label,
    ...restProps
}: VitalSignHeightCmViewProps) {
    return (
        <span
            className={`vital-sign-height-cm-view ${className}`}
            role="img"
            aria-label={label}
            data-value={value}
            {...restProps}
        >
            {value}
        </span>
    );
}

// public-good-design-system-vue-headless/components/VitalSignHeightCmView.vue
<script setup lang="ts">

    // VitalSignHeightCmView component
    //
    // A read-only display of a height value in centimeters (cm).
    // Used to present vital sign data in patient dashboards, health records,
    // and medical monitoring interfaces. Screen readers receive the full
    // description via aria-label.
    //
    // Props:
    //   value — number, required. Height in centimeters.
    //   label — string, required. Accessible description via aria-label (e.g., "175 cm height").
    //   ...restProps — additional HTML attributes spread onto the outer span.
    //
    // Syntax:
    //   <VitalSignHeightCmView :value="175" label="175 cm height" />
    //
    // Examples:
    //   <!-- Display a typical adult height -->
    //   <VitalSignHeightCmView :value="175" label="175 cm height" />
    //
    //   <!-- Display a child's height -->
    //   <VitalSignHeightCmView :value="120" label="120 cm height" />
    //
    // Keyboard:
    //   - None — this is a passive, read-only display element
    //
    // Accessibility:
    //   - role="img" on the outer span indicates it represents a visual/graphic element
    //   - aria-label provides the full value description for screen readers
    //   - data-value attribute enables consumer CSS styling
    //
    // Internationalization:
    //   - The label prop allows localized value descriptions
    //   - Consumer provides all text via props; no hardcoded strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Renders a bare <span> element
    //
    // References:
    //   - WAI-ARIA img role: https://www.w3.org/WAI/ARIA/apd/roles/img/

    defineProps<{
        /** Height in centimeters. */
        value: number;
        /** Accessible description. */
        label: string;
    }>();

</script>

<template>
    <!-- VitalSignHeightCmView.vue -->
    <span
        class="vital-sign-height-cm-view"
        role="img"
        :aria-label="label"
        :data-value="value"
    >{{ value }}</span>
</template>
