// public-good-design-system-svelte-headless/components/VitalSignVO2MaxMlPerKgPerMinuteView.svelte
<script lang="ts">
    // VitalSignVO2MaxMlPerKgPerMinuteView component
    //
    // A read-only display of a VO2 max value in ml/kg/min. This is a passive view
    // element used for showing vital sign readings in patient monitors, health
    // dashboards, medical records, and fitness applications. Screen readers receive
    // the full description via aria-label.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   value — number, required. VO2 max value in ml/kg/min to display.
    //   label — string, required. Accessible description via aria-label (e.g., "42 ml/kg/min VO2 max").
    //   ...restProps — additional HTML attributes spread onto the outer span.
    //
    // Syntax:
    //   <VitalSignVO2MaxMlPerKgPerMinuteView value={42} label="42 ml/kg/min VO2 max" />
    //
    // Examples:
    //   <!-- Display a normal VO2 max reading -->
    //   <VitalSignVO2MaxMlPerKgPerMinuteView value={42} label="42 ml/kg/min VO2 max" />
    //
    //   <!-- Display a high VO2 max reading -->
    //   <VitalSignVO2MaxMlPerKgPerMinuteView value={70} label="70 ml/kg/min VO2 max" />
    //
    // Keyboard:
    //   - None — this is a passive, read-only display element
    //
    // Accessibility:
    //   - role="img" on the span indicates it represents a visual/graphic element
    //   - aria-label provides the full VO2 max description for screen readers
    //   - data-value attribute enables consumer CSS styling based on the numeric value
    //
    // Internationalization:
    //   - The label prop allows localized VO2 max descriptions
    //   - No hardcoded user-facing strings; all text comes through props
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Companion to VitalSignVO2MaxMlPerKgPerMinuteInput for the Input/View pattern
    //
    // References:
    //   - WAI-ARIA img role: https://www.w3.org/WAI/ARIA/apd/roles/img/

    let {
        class: className = "",
        value,
        label,
        ...restProps
    }: {
        /** VO2 max value in ml/kg/min. */
        value: number;
        /** Accessible description. */
        label: string;
        [key: string]: unknown;
    } = $props();
</script>

<!-- VitalSignVO2MaxMlPerKgPerMinuteView.svelte -->
<span
    class={`vital-sign-vo2-max-ml-per-kg-per-minute-view ${className}`}
    role="img"
    aria-label={label}
    data-value={value}
    {...restProps}
>{value}</span>

// public-good-design-system-vue-headless/components/VitalSignVO2MaxMlPerKgPerMinuteView.vue
<script setup lang="ts">

    // VitalSignVO2MaxMlPerKgPerMinuteView component
    //
    // A read-only display of a VO2 max value in ml/kg/min.
    // Used to present vital sign data in patient dashboards, health records,
    // fitness tracking interfaces, and cardiorespiratory assessments. Screen
    // readers receive the full description via aria-label.
    //
    // Props:
    //   value — number, required. VO2 max in ml/kg/min.
    //   label — string, required. Accessible description via aria-label (e.g., "42 ml/kg/min VO2 max").
    //   ...restProps — additional HTML attributes spread onto the outer span.
    //
    // Syntax:
    //   <VitalSignVO2MaxMlPerKgPerMinuteView :value="42" label="42 ml/kg/min VO2 max" />
    //
    // Examples:
    //   <!-- Display a normal VO2 max -->
    //   <VitalSignVO2MaxMlPerKgPerMinuteView :value="42" label="42 ml/kg/min VO2 max" />
    //
    //   <!-- Display a high VO2 max -->
    //   <VitalSignVO2MaxMlPerKgPerMinuteView :value="60" label="60 ml/kg/min VO2 max" />
    //
    // Keyboard:
    //   - None — this is a passive, read-only display element
    //
    // Accessibility:
    //   - role="img" on the outer span indicates it represents a visual/graphic element
    //   - aria-label provides the full value description for screen readers
    //   - data-value attribute enables consumer CSS styling
    //
    // Internationalization:
    //   - The label prop allows localized value descriptions
    //   - Consumer provides all text via props; no hardcoded strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Renders a bare <span> element
    //
    // References:
    //   - WAI-ARIA img role: https://www.w3.org/WAI/ARIA/apd/roles/img/

    defineProps<{
        /** VO2 max in ml/kg/min. */
        value: number;
        /** Accessible description. */
        label: string;
    }>();

</script>

<template>
    <!-- VitalSignVO2MaxMlPerKgPerMinuteView.vue -->
    <span
        class="vital-sign-vo2-max-ml-per-kg-per-minute-view"
        role="img"
        :aria-label="label"
        :data-value="value"
    >{{ value }}</span>
</template>
