// public-good-design-system-react-headless/components/VitalSignWeightKgView.tsx
// VitalSignWeightKgView component
//
// A read-only display of a weight value in kilograms (kg). This
// component renders the numeric value as text content inside a span element with
// appropriate ARIA attributes for accessibility. It is the display-only companion
// to VitalSignWeightKgInput, used for showing weight
// readings in patient dashboards, medical records, and health monitoring displays.
//
// Props:
//   className — string, optional. CSS class name.
//   value — number, required. Weight value in kilograms.
//   label — string, required. Accessible description via aria-label (e.g., "75 kg weight").
//   ...restProps — additional HTML attributes spread onto the outer span.
//
// Syntax:
//   <VitalSignWeightKgView value={75} label="75 kg weight" />
//
// Examples:
//
//   <VitalSignWeightKgView value={75} label="75 kg weight" />
//
//
//   <VitalSignWeightKgView value={60} label="60 kg weight" />
//
// Keyboard:
//   - None — this is a passive, read-only display element
//
// Accessibility:
//   - role="img" on the outer span indicates it represents a visual/graphic element
//   - aria-label provides the full weight description for screen readers
//   - data-value attribute enables consumer CSS styling based on the value
//
// Internationalization:
//   - The label prop allows localized weight descriptions
//   - No hardcoded user-facing strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Companion to VitalSignWeightKgInput for the Input/View pattern
//
// References:
//   - WAI-ARIA img role: https://www.w3.org/WAI/ARIA/apd/roles/img/

import React from "react";

export interface VitalSignWeightKgViewProps {
    className?: string;
    /** Weight value in kilograms. */
    value: number;
    /** Accessible description. */
    label: string;
    [key: string]: unknown;
}

export default function VitalSignWeightKgView({
    className = "",
    value,
    label,
    ...restProps
}: VitalSignWeightKgViewProps) {
    return (
        <span
            className={`vital-sign-weight-kg-view ${className}`}
            role="img"
            aria-label={label}
            data-value={value}
            {...restProps}
        >
            {value}
        </span>
    );
}

// public-good-design-system-vue-headless/components/VitalSignWeightKgView.vue
<script setup lang="ts">

    // VitalSignWeightKgView component
    //
    // A read-only display of a weight value in kilograms (kg).
    // Used to present vital sign data in patient dashboards, health records,
    // and medical monitoring interfaces. Screen readers receive the full
    // description via aria-label.
    //
    // Props:
    //   value — number, required. Weight in kilograms.
    //   label — string, required. Accessible description via aria-label (e.g., "75 kg weight").
    //   ...restProps — additional HTML attributes spread onto the outer span.
    //
    // Syntax:
    //   <VitalSignWeightKgView :value="75" label="75 kg weight" />
    //
    // Examples:
    //   <!-- Display a typical adult weight -->
    //   <VitalSignWeightKgView :value="75" label="75 kg weight" />
    //
    //   <!-- Display a child's weight -->
    //   <VitalSignWeightKgView :value="30" label="30 kg weight" />
    //
    // Keyboard:
    //   - None — this is a passive, read-only display element
    //
    // Accessibility:
    //   - role="img" on the outer span indicates it represents a visual/graphic element
    //   - aria-label provides the full value description for screen readers
    //   - data-value attribute enables consumer CSS styling
    //
    // Internationalization:
    //   - The label prop allows localized value descriptions
    //   - Consumer provides all text via props; no hardcoded strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Renders a bare <span> element
    //
    // References:
    //   - WAI-ARIA img role: https://www.w3.org/WAI/ARIA/apd/roles/img/

    defineProps<{
        /** Weight in kilograms. */
        value: number;
        /** Accessible description. */
        label: string;
    }>();

</script>

<template>
    <!-- VitalSignWeightKgView.vue -->
    <span
        class="vital-sign-weight-kg-view"
        role="img"
        :aria-label="label"
        :data-value="value"
    >{{ value }}</span>
</template>
