// public-good-design-system-vue-nuxt-examples/pages/file-upload-form.vue
<script setup lang="ts">
import { ref } from "vue";

interface UploadedFile {
    name: string;
    size: number;
}

const files = ref<UploadedFile[]>([]);
const uploading = ref(false);
const progress = ref(0);
const done = ref(false);

function handleFilesChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files) {
        const newFiles = Array.from(input.files).map((f) => ({
            name: f.name,
            size: f.size,
        }));
        files.value = [...files.value, ...newFiles];
    }
}

function formatSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function removeFile(index: number) {
    files.value = files.value.filter((_, i) => i !== index);
}

function handleSubmit() {
    if (files.value.length === 0) return;
    uploading.value = true;
    progress.value = 0;

    const interval = setInterval(() => {
        progress.value += 10;
        if (progress.value >= 100) {
            clearInterval(interval);
            uploading.value = false;
            done.value = true;
        }
    }, 300);
}
</script>

<template>
    <main class="page-wrapper">
        <Form label="File upload" @submit="handleSubmit">
            <h1>Upload Documents</h1>

            <Alert v-if="done" type="success" heading="Upload complete">
                {{ files.length }} file(s) uploaded successfully.
            </Alert>

            <Field label="Select files">
                <FileUpload label="Choose files to upload">
                    <FileInput
                        label="Choose files"
                        accept=".pdf,.doc,.docx,.txt"
                        :disabled="uploading"
                        @change="handleFilesChange"
                    />
                </FileUpload>
            </Field>

            <div v-if="files.length > 0">
                <h2>Selected files</h2>
                <ul>
                    <li v-for="(file, index) in files" :key="index">
                        {{ file.name }}
                        <Badge>{{ formatSize(file.size) }}</Badge>
                        <Button v-if="!uploading && !done" @click="removeFile(index)">
                            Remove
                        </Button>
                    </li>
                </ul>
            </div>

            <Progress v-if="uploading" label="Upload progress" :value="progress" :max="100" />

            <Button type="submit" :disabled="files.length === 0 || uploading || done">
                {{ uploading ? 'Uploading...' : 'Upload Files' }}
            </Button>
        </Form>
    </main>
</template>

// public-good-design-system-react-next-examples/app/file-upload-form/page.tsx
"use client";

import { useState } from "react";
import FileUpload from "@pgds/FileUpload";
import Progress from "@pgds/Progress";
import Button from "@pgds/Button";
import Alert from "@pgds/Alert";
import Badge from "@pgds/Badge";
import Form from "@pgds/Form";
import Field from "@pgds/Field";

interface UploadedFile {
    name: string;
    size: number;
}

export default function FileUploadFormPage() {
    const [files, setFiles] = useState<UploadedFile[]>([]);
    const [uploading, setUploading] = useState(false);
    const [progress, setProgress] = useState(0);
    const [done, setDone] = useState(false);

    function handleFilesChange(fileList: FileList | null) {
        if (fileList) {
            const newFiles = Array.from(fileList).map((f) => ({
                name: f.name,
                size: f.size,
            }));
            setFiles((prev) => [...prev, ...newFiles]);
        }
    }

    function formatSize(bytes: number): string {
        if (bytes < 1024) return `${bytes} B`;
        if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
        return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    }

    function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
        event.preventDefault();
        if (files.length === 0) return;

        setUploading(true);
        setProgress(0);

        const interval = setInterval(() => {
            setProgress((prev) => {
                if (prev >= 100) {
                    clearInterval(interval);
                    setUploading(false);
                    setDone(true);
                    return 100;
                }
                return prev + 10;
            });
        }, 300);
    }

    function removeFile(index: number) {
        setFiles((prev) => prev.filter((_, i) => i !== index));
    }

    return (
        <main>
            <Form label="File upload" onSubmit={handleSubmit}>
                <h1>Upload Documents</h1>

                {done && (
                    <Alert type="success" heading="Upload complete">
                        {files.length} file(s) uploaded successfully.
                    </Alert>
                )}

                <Field label="Select files">
                    <FileUpload
                        label="Choose files to upload"
                        accept=".pdf,.doc,.docx,.txt"
                        multiple
                        onInputChange={handleFilesChange}
                        disabled={uploading}
                    />
                </Field>

                {files.length > 0 && (
                    <div>
                        <h2>Selected files</h2>
                        <ul>
                            {files.map((file, index) => (
                                <li key={index}>
                                    {file.name}
                                    <Badge>{formatSize(file.size)}</Badge>
                                    {!uploading && !done && (
                                        <Button onClick={() => removeFile(index)}>
                                            Remove
                                        </Button>
                                    )}
                                </li>
                            ))}
                        </ul>
                    </div>
                )}

                {uploading && (
                    <Progress label="Upload progress" value={progress} max={100} />
                )}

                <Button type="submit" disabled={files.length === 0 || uploading || done}>
                    {uploading ? "Uploading..." : "Upload Files"}
                </Button>
            </Form>
        </main>
    );
}
