// public-good-design-system-vue-nuxt-examples/components/ContentsListItem.vue
<script setup lang="ts">

    // ContentsListItem component
    //
    // A headless list item for use within a table of contents or navigation list.
    // Renders a semantic <li> element that wraps consumer-provided content, typically
    // an anchor link to a page section. Supports nesting for hierarchical
    // document structures by placing a `<ol>` inside. Used as a child of
    // ContentsList or any ordered/ordered list in a navigation context.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   default slot. List item content (typically a link or nested list).
    //   ...restProps — additional HTML attributes spread onto the <li>.
    //
    // Syntax:
    //   <ContentsListItem><a href="#section">Section</a></ContentsListItem>
    //
    // Examples:
    //   <!-- Nested contents list items for subsections -->
    //   <ContentsListItem>
    //     <a href="#section-3">Results</a>
    //     <ul>
    //       <ContentsListItem><a href="#section-3a">Data</a></ContentsListItem>
    //       <ContentsListItem><a href="#section-3b">Analysis</a></ContentsListItem>
    //     </ul>
    //   </ContentsListItem>
    //
    // Keyboard:
    //   - None — keyboard interaction is handled by contained links or the parent list
    //
    // Accessibility:
    //   - Semantic <li> provides implicit listitem role
    //   - Should be placed within a <ul> or <ol> parent for valid HTML structure
    //   - Supports aria-current="page" or aria-current="true" on the <li> for current page indication
    //
    // Internationalization:
    //   - All content is provided through the default slot; no hardcoded strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Compound component: used as a child within ContentsList
    //
    // References:
    //   - WAI-ARIA Menu Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/menu/

</script>

<template>
    <!-- ContentsListItem: a list item for use in a contents or navigation list -->
    <li>
        <slot />
    </li>
</template>

// public-good-design-system-react-headless/components/ContentsListItem.tsx
// ContentsListItem component
//
// A headless list item for use within a table of contents or navigation list.
// Renders a semantic <li> element that wraps consumer-provided content, typically
// an anchor link to a page section. Supports nesting for hierarchical
// document structures by placing a `<ol>` inside. Used as a child of
// ContentsList or any ordered/ordered list in a navigation context.
//
// Props:
//   className — string, optional. CSS class name.
//   children — ReactNode, required. List item content (typically a link or nested list).
//   ...restProps — additional HTML attributes spread onto the <li>.
//
// Syntax:
//   <ContentsListItem><a href="#section">Section</a></ContentsListItem>
//
// Examples:
//   
//   <ContentsListItem>
//     <a href="#section-3">Results</a>
//     <ul>
//       <ContentsListItem><a href="#section-3a">Data</a></ContentsListItem>
//       <ContentsListItem><a href="#section-3b">Analysis</a></ContentsListItem>
//     </ul>
//   </ContentsListItem>
//
// Keyboard:
//   - None — keyboard interaction is handled by contained links or the parent list
//
// Accessibility:
//   - Semantic <li> provides implicit listitem role
//   - Should be placed within a <ul> or <ol> parent for valid HTML structure
//   - Supports aria-current="page" or aria-current="true" on the <li> for current page indication
//
// Internationalization:
//   - All content is provided through the children prop; no hardcoded strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Compound component: used as a child within ContentsList
//
// References:
//   - WAI-ARIA Menu Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/menu/

import React from "react";

export interface ContentsListItemProps {
    className?: string;
    /** List item content (typically a link or text) */
    children: React.ReactNode;
    /** Additional HTML attributes */
    [key: string]: unknown;
}

export default function ContentsListItem({
    className = "",
    children,
    ...restProps
}: ContentsListItemProps) {
    return (
        
        <li {...restProps}>
        {children}
        </li>
    );
}
