// public-good-design-system-vue-nuxt-examples/components/GanttTable.vue
<script setup lang="ts">

    // GanttTable component
    //
    // An interactive Gantt table that displays project tasks and their timelines
    // as a structured grid widget. Renders a <table> element with role="grid" and
    // an accessible label. Supports an optional visible caption. Commonly used in
    // project management tools and resource planning applications.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   label — string, required. Accessible name describing the Gantt table content.
    //   caption — string, optional. Visible caption text displayed above the table.
    //   default slot. GanttTableHead, GanttTableBody, GanttTableFoot elements.
    //   ...restProps — additional HTML attributes spread onto the <table>.
    //
    // Syntax:
    //   <GanttTable label="Project timeline">
    //     <GanttTableHead>
    //       <GanttTableRow>
    //         <th>Task</th><th>Week 1</th><th>Week 2</th><th>Week 3</th>
    //       </GanttTableRow>
    //     </GanttTableHead>
    //     <GanttTableBody>
    //       <GanttTableRow>
    //         <th>Design</th>
    //         <GanttTableData active>---</GanttTableData>
    //         <GanttTableData />
    //         <GanttTableData />
    //       </GanttTableRow>
    //     </GanttTableBody>
    //   </GanttTable>
    //
    // Keyboard:
    //   None built-in — consumer should implement grid keyboard navigation
    //   (arrow keys for cell movement, Enter/Space for selection).
    //
    // Accessibility:
    //   - role="grid" identifies the table as an interactive grid widget
    //   - aria-label provides an accessible name describing the Gantt table
    //   - <caption> provides a visible accessible name when the caption prop is set
    //
    // Internationalization:
    //   - The label and caption props provide all text; no hardcoded strings
    //   - All content comes through the default slot
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Compound component: use with GanttTableHead, GanttTableBody, GanttTableFoot,
    //     GanttTableRow, GanttTableData, and GanttTableCol
    //
    // References:
    //   - WAI-ARIA Grid Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/grid/

    withDefaults(defineProps<{
        /** Accessible name describing the Gantt table content. */
        label: string;
        /** Visible caption for the table. */
        caption?: string;
    }>(), {
        caption: undefined,
    });

</script>

<template>
    <!-- GanttTable.vue -->
    <table
        class="gantt-table"
        role="grid"
        :aria-label="label"
    >
                <caption v-if="caption">{{ caption }}</caption>
        <slot />
    </table>
</template>

// public-good-design-system-react-headless/components/GanttTable.tsx
// GanttTable component
//
// An interactive Gantt table that displays project tasks and their timelines
// as a structured grid widget. Renders a <table> element with role="grid" and
// an accessible label. Supports an optional visible caption. Commonly used in
// project management tools and resource planning applications.
//
// Props:
//   className — string, optional. CSS class name.
//   label — string, required. Accessible name describing the Gantt table content.
//   caption — string, optional. Visible caption text displayed above the table.
//   children — ReactNode, required. GanttTableHead, GanttTableBody, GanttTableFoot elements.
//   ...restProps — additional HTML attributes spread onto the <table>.
//
// Syntax:
//   <GanttTable label="Project timeline">
//     <GanttTableHead>
//       <GanttTableRow>
//         <th>Task</th><th>Week 1</th><th>Week 2</th><th>Week 3</th>
//       </GanttTableRow>
//     </GanttTableHead>
//     <GanttTableBody>
//       <GanttTableRow>
//         <th>Design</th>
//         <GanttTableData active>---</GanttTableData>
//         <GanttTableData />
//         <GanttTableData />
//       </GanttTableRow>
//     </GanttTableBody>
//   </GanttTable>
//
// Keyboard:
//   None built-in — consumer should implement grid keyboard navigation
//   (arrow keys for cell movement, Enter/Space for selection).
//
// Accessibility:
//   - role="grid" identifies the table as an interactive grid widget
//   - aria-label provides an accessible name describing the Gantt table
//   - <caption> provides a visible accessible name when the caption prop is set
//
// Internationalization:
//   - The label and caption props provide all text; no hardcoded strings
//   - All content comes through the children prop
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Compound component: use with GanttTableHead, GanttTableBody, GanttTableFoot,
//     GanttTableRow, GanttTableData, and GanttTableCol
//
// References:
//   - WAI-ARIA Grid Pattern: https://www.w3.org/WAI/ARIA/apd/patterns/grid/

import React from "react";

export interface GanttTableProps {
    className?: string;
    /** Accessible name describing the Gantt table content. */
    label: string;
    /** Visible caption for the table. */
    caption?: string;
    /** GanttTableHead, GanttTableBody, GanttTableFoot elements. */
    children: React.ReactNode;
    [key: string]: unknown;
}

export default function GanttTable({
    className = "",
    label,
    caption = undefined,
    children,
    ...restProps
}: GanttTableProps) {
    return (
        <table
        className={`gantt-table ${className}`}
        role="grid"
        aria-label={label}
        {...restProps}
        >
        {caption && (<><caption>{caption}</caption></>)}
        {children}
        </table>
    );
}
