// public-good-design-system-vue-headless/components/InsetText.vue
<script setup lang="ts">

    // InsetText component
    //
    // An inset text block used to distinguish content from the surrounding text, drawing
    // attention to important information that a user needs to know. Commonly used in
    // government and institutional design systems to highlight supplementary information,
    // processing times, eligibility criteria, or important notices. Renders a <div> with
    // role="note" for semantic supplementary content indication.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   default slot. Content to display inside the inset text block.
    //   ...restProps — additional HTML attributes spread onto the container div.
    //
    // Syntax:
    //   <InsetText>It can take up to 8 weeks to process.</InsetText>
    //
    // Examples:
    //   <!-- Simple inset text notice -->
    //   <InsetText>It can take up to 8 weeks to process.</InsetText>
    //
    //   <!-- Inset text with structured content -->
    //   <InsetText>
    //     <p>You must apply before the deadline. Late applications will not be accepted.</p>
    //   </InsetText>
    //
    // Keyboard:
    //   - None — this is a passive container with no interactive behavior
    //
    // Accessibility:
    //   - role="note" identifies the content as supplementary information
    //   - Screen readers announce it with appropriate context as a note
    //
    // Internationalization:
    //   - All content comes through the default slot; no hardcoded user-facing strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling (e.g., border-left, indentation)
    //   - No internal state; purely a presentational container
    //   - Inspired by GOV.UK and NHS England "inset text" pattern
    //
    // References:
    //   - WAI-ARIA Note Role: https://www.w3.org/TR/wai-aria-1.2/#note
    //   - GOV.UK Inset Text: https://design-system.service.gov.uk/components/inset-text/
    //   - NHS England Inset Text: https://service-manual.nhs.uk/design-system/components/inset-text

</script>

<template>
    <!-- InsetText.vue -->
    <div
        class="inset-text"
        role="note"
    >
        <slot />
    </div>
</template>

// public-good-design-system-react-headless/components/InsetText.tsx
// InsetText component
//
// An inset text block used to distinguish content from the surrounding text, drawing
// attention to important information that a user needs to know. Commonly used in
// government and institutional design systems to highlight supplementary information,
// processing times, eligibility criteria, or important notices. Renders a <div> with
// role="note" for semantic supplementary content indication.
//
// Props:
//   className — string, optional. CSS class name.
//   children — ReactNode, required. Content to display inside the inset text block.
//   ...restProps — additional HTML attributes spread onto the container div.
//
// Syntax:
//   <InsetText>It can take up to 8 weeks to process.</InsetText>
//
// Examples:
//   
//   <InsetText>It can take up to 8 weeks to process.</InsetText>
//
//   
//   <InsetText>
//     <p>You must apply before the deadline. Late applications will not be accepted.</p>
//   </InsetText>
//
// Keyboard:
//   - None — this is a passive container with no interactive behavior
//
// Accessibility:
//   - role="note" identifies the content as supplementary information
//   - Screen readers announce it with appropriate context as a note
//
// Internationalization:
//   - All content comes through the children prop; no hardcoded user-facing strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling (e.g., border-left, indentation)
//   - No internal state; purely a presentational container
//   - Inspired by GOV.UK and NHS England "inset text" pattern
//
// References:
//   - WAI-ARIA Note Role: https://www.w3.org/TR/wai-aria-1.2/#note
//   - GOV.UK Inset Text: https://design-system.service.gov.uk/components/inset-text/
//   - NHS England Inset Text: https://service-manual.nhs.uk/design-system/components/inset-text

import React from "react";

export interface InsetTextProps {
    className?: string;
    children: React.ReactNode;
    [key: string]: unknown;
}

export default function InsetText({
    className = "",
    children,
    ...restProps
}: InsetTextProps) {
    return (
        <div
        className={`inset-text ${className}`}
        role="note"
        {...restProps}
        >
        {children}
        </div>
    );
}
