// public-good-design-system-vue-headless/components/PasswordInput.vue
<script setup lang="ts">

    // PasswordInput component
    //
    // A headless password input using the native HTML <input type="password">
    // element. Renders a single password field with obscured text entry and
    // browser password manager integration via autocomplete. Unlike
    // PasswordInputOrTextInputDiv, this component renders only the bare <input> element
    // without a wrapper or toggle button. Commonly used in login forms,
    // registration forms, and account settings.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   label — string, required. Accessible name via aria-label.
    //   value — string, default "". Bindable password value; supports v-model.
    //   autocomplete — string, default "current-password". Autocomplete hint for browsers.
    //   required — boolean, default false. Whether the field is required.
    //   disabled — boolean, default false. Whether the field is disabled.
    //   ...restProps — additional HTML attributes spread onto the <input>.
    //
    // Syntax:
    //   <PasswordInput label="Password" v-model />
    //
    // Examples:
    //   <!-- Required password field -->
    //   <PasswordInput label="Password" v-model required />
    //
    //   <!-- New password with autocomplete hint -->
    //   <PasswordInput label="New password" v-model autocomplete="new-password" />
    //
    //   <!-- Disabled password field -->
    //   <PasswordInput label="Password" v-model disabled />
    //
    // Keyboard:
    //   - None beyond native input behavior -- standard text editing keys
    //
    // Accessibility:
    //   - aria-label={label} provides an accessible name since no visible <label> is included
    //   - autocomplete attribute enables browser password manager integration
    //
    // Internationalization:
    //   - The label prop accepts any translated string
    //   - No hardcoded user-facing strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles -- consumer provides all styling
    //   - Uses defineModel() for two-way data binding on value
    //   - Consumer can add placeholder, maxlength, pattern via restProps
    //
    // References:
    //   - MDN input type="password": https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password

    withDefaults(defineProps<{
        /** Accessible label. */
        label: string;
        /** Autocomplete hint for browsers. */
        autocomplete?: string;
        /** Whether required. */
        required?: boolean;
        /** Whether disabled. */
        disabled?: boolean;
    }>(), {
        autocomplete: "current-password",
        required: false,
        disabled: false,
    });

    const modelValue = defineModel<string>({ default: "" });

</script>

<template>
    <!-- PasswordInput.vue -->
    <input
        class="password-input"
        type="password"
        :aria-label="label"
        v-model="modelValue"
        :autocomplete="autocomplete"
        :required="required"
        :disabled="disabled"
    />
</template>

// public-good-design-system-react-headless/components/PasswordInput.tsx
// PasswordInput component
//
// A headless password field using the native HTML <input type="password">
// element. It renders a single input that obscures the entered text. Unlike
// PasswordInputOrTextInputDiv, this component does not include a show/hide toggle — it
// is a simple, single-element password input. Includes autocomplete support
// for browser password manager integration.
//
// Props:
//   className — string, optional. CSS class name.
//   label — string, required. Accessible name via aria-label.
//   value — string, default "". Current password value; bindable with value + onChange.
//   autocomplete — string, default "current-password". Autocomplete hint for browser password managers.
//   required — boolean, default false. Whether the field must be filled before form submission.
//   disabled — boolean, default false. Whether the input is disabled.
//   onChange — function, optional. Callback when value changes.
//   ...restProps — additional HTML attributes spread onto the <input>.
//
// Syntax:
//   <PasswordInput label="Password" value={value} onChange={setValue} />
//
// Examples:
//
//   <PasswordInput label="Password" value={value} onChange={setValue} />
//
//
//   <PasswordInput label="New password" value={value} onChange={setValue} autocomplete="new-password" />
//
//
//   <PasswordInput label="Mot de passe" value={value} onChange={setValue} required />
//
// Keyboard:
//   - Tab: moves focus to the input (standard behavior)
//   - Enter: submits the containing form (standard input behavior)
//
// Accessibility:
//   - aria-label provides the accessible name since there is no visible <label> element
//   - autocomplete="current-password" enables browser password manager integration
//   - Native <input type="password"> provides built-in text obscuring
//
// Internationalization:
//   - The label prop externalizes the accessible name for localization
//   - No other hardcoded user-facing strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Value uses controlled pattern with value + onChange
//   - No visible <label> element — relies on aria-label
//
// References:
//   - MDN input type="password": https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password

import React from "react";

export interface PasswordInputProps {
    className?: string;
    /** Accessible label. */
    label: string;
    /** Current value. Bindable. */
    value?: string;
    /** Autocomplete hint. */
    autocomplete?: string;
    /** Whether required. */
    required?: boolean;
    /** Whether disabled. */
    disabled?: boolean;
    /** Callback when value changes. */
    onChange?: (value: string) => void;
    [key: string]: unknown;
}

export default function PasswordInput({
    className = "",
    label,
    value = "",
    autocomplete = "current-password",
    required = false,
    disabled = false,
    onChange,
    ...restProps
}: PasswordInputProps) {
    return (
        <input
        className={`password-input ${className}`}
        type="password"
        aria-label={label}
        value={value}
        onChange={(e) => onChange?.(e.target.value)}
        autoComplete={autocomplete}
        required={required}
        disabled={disabled}
        {...restProps}
        />
    );
}
