// public-good-design-system-vue-nuxt-examples/components/SkipLink.vue
<script setup lang="ts">

    // SkipLink component
    //
    // A headless skip navigation link that allows keyboard users to bypass
    // repetitive content (navigation menus, headers) and jump directly to the main
    // content area. Should be the very first focusable element on a page. Typically
    // styled to be visually hidden until focused, then positioned prominently.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   href — string, default "#content". The anchor target that the link navigates to.
    //   label — string, default "Skip to content". The visible link text.
    //   ...restProps — additional HTML attributes spread onto the <a>.
    //
    // Syntax:
    //   <SkipLink />
    //
    // Examples:
    //   <!-- Custom target and label -->
    //   <SkipLink href="#main" label="Skip to main content" />
    //
    //   <!-- With custom class for focus styling -->
    //   <SkipLink href="#content" label="Skip navigation" class="sr-only-focusable" />
    //
    // Keyboard:
    //   - Tab: moves focus to the skip link (should be the first focusable element)
    //   - Enter: activates the link, moving focus to the target anchor element
    //
    // Accessibility:
    //   - Native <a> element with href is natively accessible as a link
    //   - The link text content (label prop) serves as the accessible name
    //   - No additional ARIA attributes needed
    //   - WCAG 2.1 Success Criterion 2.4.1: Bypass Blocks
    //
    // Internationalization:
    //   - The label prop externalizes the link text for localization
    //   - Default "Skip to content" should be overridden in non-English contexts
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Consumer must ensure the target element exists with a matching id attribute
    //   - Typically styled as visually hidden until :focus
    //
    // References:
    //   - WCAG 2.1 Bypass Blocks: https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html
    //   - WebAIM Skip Navigation Links: https://webaim.org/techniques/skipnav/

    withDefaults(defineProps<{
        /** Target anchor. */
        href?: string;
        /** Link text. */
        label?: string;
    }>(), {
        href: "#content",
        label: "Skip to content",
    });

</script>

<template>
    <!-- SkipLink.vue -->
    <a
        class="skip-link"
        :href="href">{{ label }}</a
    >
</template>

// public-good-design-system-react-headless/components/SkipLink.tsx
// SkipLink component
//
// A headless skip navigation link that allows keyboard users to bypass
// repetitive content (navigation menus, headers) and jump directly to the main
// content area. Should be the very first focusable element on a page. Typically
// styled to be visually hidden until focused, then positioned prominently.
//
// Props:
//   className — string, optional. CSS class name.
//   href — string, default "#content". The anchor target that the link navigates to.
//   label — string, default "Skip to content". The visible link text.
//   ...restProps — additional HTML attributes spread onto the <a>.
//
// Syntax:
//   <SkipLink />
//
// Examples:
//   
//   <SkipLink href="#main" label="Skip to main content" />
//
//   
//   <SkipLink href="#content" label="Skip navigation" class="sr-only-focusable" />
//
// Keyboard:
//   - Tab: moves focus to the skip link (should be the first focusable element)
//   - Enter: activates the link, moving focus to the target anchor element
//
// Accessibility:
//   - Native <a> element with href is natively accessible as a link
//   - The link text content (label prop) serves as the accessible name
//   - No additional ARIA attributes needed
//   - WCAG 2.1 Success Criterion 2.4.1: Bypass Blocks
//
// Internationalization:
//   - The label prop externalizes the link text for localization
//   - Default "Skip to content" should be overridden in non-English contexts
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Consumer must ensure the target element exists with a matching id attribute
//   - Typically styled as visually hidden until :focus
//
// References:
//   - WCAG 2.1 Bypass Blocks: https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html
//   - WebAIM Skip Navigation Links: https://webaim.org/techniques/skipnav/

import React from "react";

export interface SkipLinkProps {
    className?: string;
    /** Target anchor. */
    href?: string;
    /** Link text. */
    label?: string;
    [key: string]: unknown;
}

export default function SkipLink({
    className = "",
    href = "#content",
    label = "Skip to content",
    ...restProps
}: SkipLinkProps) {
    return (
        <a
        className={`skip-link ${className}`}
        href={href}
        {...restProps}>{label}</a
        >
    );
}
