// public-good-design-system-svelte-sveltekit-examples/src/routes/navigation-and-menus/+page.svelte
<script lang="ts">
    import NavigationMenu from "$lib/components/NavigationMenu.svelte";
    import MenuBar from "$lib/components/MenuBar.svelte";
    import MenuBarButton from "$lib/components/MenuBarButton.svelte";
    import Menu from "$lib/components/Menu.svelte";
    import MenuItem from "$lib/components/MenuItem.svelte";
    import ToolBar from "$lib/components/ToolBar.svelte";
    import ToolBarButton from "$lib/components/ToolBarButton.svelte";
    import HamburgerMenu from "$lib/components/HamburgerMenu.svelte";
    import DropdownMenu from "$lib/components/DropdownMenu.svelte";
    import ContextMenu from "$lib/components/ContextMenu.svelte";
    import ContextMenuItem from "$lib/components/ContextMenuItem.svelte";
    import ActionLink from "$lib/components/ActionLink.svelte";
    import BackLink from "$lib/components/BackLink.svelte";
    import PaginationNav from "$lib/components/PaginationNav.svelte";
    import PaginationList from "$lib/components/PaginationList.svelte";
    import PaginationListItem from "$lib/components/PaginationListItem.svelte";
    import Header from "$lib/components/Header.svelte";
    import Footer from "$lib/components/Footer.svelte";

    let showDropdown = $state(false);
    let showContext = $state(false);
    let hamburgerOpen = $state(false);
    let currentPage = $state(3);
</script>

<Header label="Site header">
    <div class="page-wrapper">
        <h1>Navigation & Menus</h1>
        <NavigationMenu label="Main navigation">
            <a href="/">Home</a>
            <a href="/dashboard">Dashboard</a>
            <a href="/contact-form">Contact</a>
            <a href="/settings-page">Settings</a>
        </NavigationMenu>
    </div>
</Header>

<main class="page-wrapper">
    <BackLink href="/">Back to examples</BackLink>

    <h2>Menu Bar</h2>
    <MenuBar label="Application menu">
        <MenuBarButton>File</MenuBarButton>
        <MenuBarButton>Edit</MenuBarButton>
        <MenuBarButton>View</MenuBarButton>
        <MenuBarButton>Help</MenuBarButton>
    </MenuBar>

    <h2>Tool Bar</h2>
    <ToolBar label="Editing toolbar">
        <ToolBarButton>Bold</ToolBarButton>
        <ToolBarButton>Italic</ToolBarButton>
        <ToolBarButton>Underline</ToolBarButton>
        <ToolBarButton disabled>Strikethrough</ToolBarButton>
    </ToolBar>

    <h2>Menu</h2>
    <Menu label="Actions menu">
        <MenuItem>New document</MenuItem>
        <MenuItem>Open file</MenuItem>
        <MenuItem>Save</MenuItem>
        <MenuItem>Export as PDF</MenuItem>
    </Menu>

    <h2>Hamburger Menu</h2>
    <div style="background: var(--nhs-dark-grey); padding: var(--nhs-space-3); border-radius: var(--nhs-border-radius); display: inline-block;">
        <HamburgerMenu label="Mobile menu" bind:open={hamburgerOpen}>
            <div style="padding: var(--nhs-space-3); background: var(--nhs-white); border-radius: var(--nhs-border-radius);">
                <nav>
                    <ul style="list-style: none; padding: 0; margin: 0;">
                        <li style="padding: var(--nhs-space-2) 0;"><a href="/">Home</a></li>
                        <li style="padding: var(--nhs-space-2) 0;"><a href="/dashboard">Dashboard</a></li>
                        <li style="padding: var(--nhs-space-2) 0;"><a href="/settings-page">Settings</a></li>
                    </ul>
                </nav>
            </div>
        </HamburgerMenu>
    </div>

    <h2>Dropdown Menu</h2>
    <div style="position: relative; display: inline-block;">
        <button class="button" onclick={() => showDropdown = !showDropdown}>Actions</button>
        <DropdownMenu label="Quick actions" bind:open={showDropdown}>
            <MenuItem>Edit profile</MenuItem>
            <MenuItem>Change password</MenuItem>
            <MenuItem>Sign out</MenuItem>
        </DropdownMenu>
    </div>

    <h2>Context Menu</h2>
    <div style="position: relative; border: 2px dashed var(--nhs-mid-grey); padding: var(--nhs-space-5); text-align: center; margin-bottom: var(--nhs-space-4); border-radius: var(--nhs-border-radius);"
         role="region"
         aria-label="Context menu demo area"
         oncontextmenu={(e) => { e.preventDefault(); showContext = !showContext; }}>
        <p>Right-click in this area to open the context menu</p>
        <ContextMenu label="Item actions" bind:open={showContext}>
            <ContextMenuItem>Copy</ContextMenuItem>
            <ContextMenuItem>Paste</ContextMenuItem>
            <ContextMenuItem>Delete</ContextMenuItem>
        </ContextMenu>
    </div>

    <h2>Action Links</h2>
    <div style="display: flex; flex-direction: column; gap: var(--nhs-space-2); margin-bottom: var(--nhs-space-4);">
        <ActionLink href="/contact-form">Book an appointment</ActionLink>
        <ActionLink href="/dashboard">View your records</ActionLink>
        <ActionLink href="/settings-page">Manage your account</ActionLink>
    </div>

    <h2>Pagination</h2>
    <PaginationNav label="Results pagination">
        <PaginationList label="Page list">
            {#each [1, 2, 3, 4, 5] as page}
                <PaginationListItem>
                    {#if page === currentPage}
                        <span aria-current="page">{page}</span>
                    {:else}
                        <a href="#{page}" onclick={(e) => { e.preventDefault(); currentPage = page; }}>{page}</a>
                    {/if}
                </PaginationListItem>
            {/each}
        </PaginationList>
    </PaginationNav>
</main>

<Footer label="Site footer">
    <div class="page-wrapper">
        <p>Public Good Design System — Navigation & Menus Example</p>
    </div>
</Footer>

// public-good-design-system-react-headless/examples/NavigationAndMenus.tsx
// Example: Navigation patterns with menus, toolbars, and mobile hamburger
//
// Demonstrates: NavigationMenu, MenuBar, MenuBarButton, ToolBar, ToolBarButton,
// HamburgerMenu, DropdownMenu, Separator

import { useState } from "react";
import NavigationMenu from "../components/NavigationMenu";
import MenuBar from "../components/MenuBar";
import MenuBarButton from "../components/MenuBarButton";
import ToolBar from "../components/ToolBar";
import ToolBarButton from "../components/ToolBarButton";
import HamburgerMenu from "../components/HamburgerMenu";
import DropdownMenu from "../components/DropdownMenu";
import Separator from "../components/Separator";

export default function NavigationAndMenus() {
    const [hamburgerOpen, setHamburgerOpen] = useState(false);
    const [fileMenuOpen, setFileMenuOpen] = useState(false);
    const [editMenuOpen, setEditMenuOpen] = useState(false);

    return (
        <div>
            <h1>Navigation and Menu Patterns</h1>

            {/* Primary site navigation */}
            <NavigationMenu label="Main navigation">
                <a href="#home">Home</a>
                <a href="#projects">Projects</a>
                <a href="#team">Team</a>
                <a href="#reports">Reports</a>
                <a href="#settings">Settings</a>
            </NavigationMenu>

            <Separator label="Section divider" />

            {/* Application menu bar */}
            <h2>Application Menu Bar</h2>
            <MenuBar label="Application menu">
                <MenuBarButton onClick={() => setFileMenuOpen(!fileMenuOpen)}>
                    File
                </MenuBarButton>
                <MenuBarButton onClick={() => setEditMenuOpen(!editMenuOpen)}>
                    Edit
                </MenuBarButton>
                <MenuBarButton>View</MenuBarButton>
                <MenuBarButton>Help</MenuBarButton>
            </MenuBar>

            {/* Dropdown menus for File and Edit */}
            <div>
                <DropdownMenu label="File" open={fileMenuOpen} onChange={setFileMenuOpen}>
                    <li role="menuitem" tabIndex={-1}>New Document</li>
                    <li role="menuitem" tabIndex={-1}>Open...</li>
                    <li role="menuitem" tabIndex={-1}>Save</li>
                    <li role="menuitem" tabIndex={-1}>Export as PDF</li>
                </DropdownMenu>

                <DropdownMenu label="Edit" open={editMenuOpen} onChange={setEditMenuOpen}>
                    <li role="menuitem" tabIndex={-1}>Undo</li>
                    <li role="menuitem" tabIndex={-1}>Redo</li>
                    <li role="menuitem" tabIndex={-1}>Cut</li>
                    <li role="menuitem" tabIndex={-1}>Copy</li>
                    <li role="menuitem" tabIndex={-1}>Paste</li>
                </DropdownMenu>
            </div>

            <Separator />

            {/* Document editing toolbar */}
            <h2>Document Toolbar</h2>
            <ToolBar label="Document formatting">
                <ToolBarButton>Bold</ToolBarButton>
                <ToolBarButton>Italic</ToolBarButton>
                <ToolBarButton>Underline</ToolBarButton>
                <ToolBarButton disabled>Strikethrough</ToolBarButton>
                <ToolBarButton>Align Left</ToolBarButton>
                <ToolBarButton>Align Center</ToolBarButton>
                <ToolBarButton>Align Right</ToolBarButton>
            </ToolBar>

            <Separator />

            {/* Mobile hamburger menu */}
            <h2>Mobile Navigation</h2>
            <HamburgerMenu
                label="Mobile menu"
                open={hamburgerOpen}
                onChange={setHamburgerOpen}
            >
                <ul>
                    <li><a href="#home">Home</a></li>
                    <li><a href="#projects">Projects</a></li>
                    <li><a href="#team">Team</a></li>
                    <li><a href="#reports">Reports</a></li>
                    <li><a href="#settings">Settings</a></li>
                    <li><a href="#profile">Profile</a></li>
                    <li><a href="#logout">Log Out</a></li>
                </ul>
            </HamburgerMenu>
        </div>
    );
}
