// public-good-design-system-vue-nuxt-examples/pages/rating-and-feedback.vue
<script setup lang="ts">
import { ref } from "vue";

const stars = ref(0);
const satisfaction = ref(0);
const nps = ref(0);
const comment = ref("");
const submitted = ref(false);

function handleSubmit() {
    submitted.value = true;
}
</script>

<template>
    <main class="page-wrapper">
        <template v-if="submitted">
            <Alert type="success" heading="Thank you!">
                Your feedback has been recorded.
            </Alert>
            <div>
                <p>Your product rating:</p>
                <FiveStarRatingView label="Your rating" :value="stars" />
            </div>
        </template>

        <template v-else>
            <h1>Feedback</h1>
            <Form label="Feedback form" @submit="handleSubmit">
                <h2>We value your feedback</h2>

                <section class="section">
                    <h3>Rate this product</h3>
                    <FiveStarRatingPicker label="Product rating" v-model="stars" />
                </section>

                <Separator />

                <section class="section">
                    <h3>How satisfied are you with our service?</h3>
                    <FiveFaceRatingPicker label="Service satisfaction" v-model="satisfaction" />
                </section>

                <Separator />

                <section class="section">
                    <h3>How likely are you to recommend us?</h3>
                    <NetPromoterScorePicker label="Recommendation likelihood" v-model="nps" />
                </section>

                <Separator />

                <section class="section">
                    <h3>Additional comments</h3>
                    <Textarea label="Comments" v-model="comment" :rows="4" />
                </section>

                <Button type="submit">Submit Feedback</Button>
            </Form>
        </template>
    </main>
</template>

// public-good-design-system-react-headless/examples/RatingAndFeedback.tsx
// Example: Rating and feedback collection
//
// Demonstrates: FiveStarRatingPicker, FiveStarRatingView, FiveFaceRatingPicker,
// NetPromoterScorePicker, Textarea, Button, Alert, Form

import { useState } from "react";
import FiveStarRatingPicker from "../components/FiveStarRatingPicker";
import FiveStarRatingView from "../components/FiveStarRatingView";
import FiveFaceRatingPicker from "../components/FiveFaceRatingPicker";
import NetPromoterScorePicker from "../components/NetPromoterScorePicker";
import Textarea from "../components/Textarea";
import Button from "../components/Button";
import Alert from "../components/Alert";
import Form from "../components/Form";
import Separator from "../components/Separator";

export default function RatingAndFeedback() {
    const [stars, setStars] = useState(0);
    const [satisfaction, setSatisfaction] = useState(0);
    const [nps, setNps] = useState(0);
    const [comment, setComment] = useState("");
    const [submitted, setSubmitted] = useState(false);

    function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
        event.preventDefault();
        setSubmitted(true);
    }

    if (submitted) {
        return (
            <div>
                <Alert type="success" heading="Thank you!">
                    Your feedback has been recorded.
                </Alert>
                <div>
                    <p>Your product rating:</p>
                    <FiveStarRatingView label="Your rating" value={stars} />
                </div>
            </div>
        );
    }

    return (
        <Form label="Feedback form" onSubmit={handleSubmit}>
            <h2>We value your feedback</h2>

            <div>
                <h3>Rate this product</h3>
                <FiveStarRatingPicker
                    label="Product rating"
                    value={stars}
                    onChange={setStars}
                />
            </div>

            <Separator />

            <div>
                <h3>How satisfied are you with our service?</h3>
                <FiveFaceRatingPicker
                    label="Service satisfaction"
                    value={satisfaction}
                    onChange={setSatisfaction}
                />
            </div>

            <Separator />

            <div>
                <h3>How likely are you to recommend us?</h3>
                <NetPromoterScorePicker
                    label="Recommendation likelihood"
                    value={nps}
                    onChange={setNps}
                />
            </div>

            <Separator />

            <div>
                <h3>Additional comments</h3>
                <Textarea
                    label="Comments"
                    value={comment}
                    onChange={setComment}
                    rows={4}
                />
            </div>

            <Button type="submit">Submit Feedback</Button>
        </Form>
    );
}
