// public-good-design-system-react-headless/components/CareCard.tsx
// CareCard component
//
// A headless healthcare guidance component inspired by NHS England care card
// patterns. Renders a <section> landmark with a heading and body content,
// supporting three urgency tiers: non-urgent (speak to a GP), urgent (visit
// A&E or call 111), and immediate (call 999). The data-type attribute enables
// consumer CSS styling based on urgency level.
//
// Props:
//   className — string, optional. CSS class name.
//   type — "non-urgent" | "urgent" | "immediate", default "non-urgent". Urgency level.
//   heading — string, required. Heading text describing the care action.
//   label — string, optional. aria-label override; defaults to heading text.
//   children — ReactNode, required. The care card body content.
//   ...restProps — additional HTML attributes spread onto the <section>.
//
// Syntax:
//   <CareCard heading="See a GP if:">
//     <p>You have persistent symptoms.</p>
//   </CareCard>
//
// Examples:
//   
//   <CareCard type="non-urgent" heading="Speak to a GP if:">
//     <ul><li>you have symptoms for more than 3 days</li></ul>
//   </CareCard>
//
//   
//   <CareCard type="immediate" heading="Call 999 if:">
//     <ul><li>you have difficulty breathing</li></ul>
//   </CareCard>
//
// Keyboard:
//   None — this component is a passive content container.
//
// Accessibility:
//   - role="region" identifies the card as a named landmark
//   - aria-label set from label prop or heading prop for screen reader identification
//   - <h2> heading provides document structure
//   - data-type exposes urgency level for consumer styling hooks
//
// Internationalization:
//   - All text comes through heading, label, and children props; no hardcoded strings
//
// Claude rules:
//   - Headless: no CSS, no styles — consumer provides all styling
//   - Consumer uses data-type attribute to apply urgency-appropriate visual styles
//
// References:
//   - NHS England Care Cards: https://service-manual.nhs.uk/design-system/components/care-cards

import React from "react";

export interface CareCardProps {
    className?: string;
    type?: "non-urgent" | "urgent" | "immediate";
    heading: string;
    label?: string;
    children: React.ReactNode;
    [key: string]: unknown;
}

export default function CareCard({
    className = "",
    type = "non-urgent",
    heading,
    label = undefined,
    children,
    ...restProps
}: CareCardProps) {
    return (
        <section
        className={`care-card ${className}`}
        role="region"
        aria-label={label ?? heading}
        data-type={type}
        {...restProps}
        >
        <h2>{heading}</h2>
        {children}
        </section>
    );
}

// public-good-design-system-vue-nuxt-examples/components/CareCard.vue
<script setup lang="ts">

    // CareCard component
    //
    // A headless healthcare guidance component inspired by NHS England care card
    // patterns. Renders a <section> landmark with a heading and body content,
    // supporting three urgency tiers: non-urgent (speak to a GP), urgent (visit
    // A&E or call 111), and immediate (call 999). The data-type attribute enables
    // consumer CSS styling based on urgency level.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   type — "non-urgent" | "urgent" | "immediate", default "non-urgent". Urgency level.
    //   heading — string, required. Heading text describing the care action.
    //   label — string, optional. aria-label override; defaults to heading text.
    //   default slot. The care card body content.
    //   ...restProps — additional HTML attributes spread onto the <section>.
    //
    // Syntax:
    //   <CareCard heading="See a GP if:">
    //     <p>You have persistent symptoms.</p>
    //   </CareCard>
    //
    // Examples:
    //   <!-- Non-urgent care card -->
    //   <CareCard type="non-urgent" heading="Speak to a GP if:">
    //     <ul><li>you have symptoms for more than 3 days</li></ul>
    //   </CareCard>
    //
    //   <!-- Immediate care card -->
    //   <CareCard type="immediate" heading="Call 999 if:">
    //     <ul><li>you have difficulty breathing</li></ul>
    //   </CareCard>
    //
    // Keyboard:
    //   None — this component is a passive content container.
    //
    // Accessibility:
    //   - role="region" identifies the card as a named landmark
    //   - aria-label set from label prop or heading prop for screen reader identification
    //   - <h2> heading provides document structure
    //   - data-type exposes urgency level for consumer styling hooks
    //
    // Internationalization:
    //   - All text comes through heading, label, and children props; no hardcoded strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling
    //   - Consumer uses data-type attribute to apply urgency-appropriate visual styles
    //
    // References:
    //   - NHS England Care Cards: https://service-manual.nhs.uk/design-system/components/care-cards

    withDefaults(defineProps<{
        type?: "non-urgent" | "urgent" | "immediate";
        heading: string;
        label?: string;
    }>(), {
        type: "non-urgent",
        label: undefined,
    });

</script>

<template>
    <!-- CareCard.vue -->
    <section
        class="care-card"
        role="region"
        :aria-label="label ?? heading"
        :data-type="type"
    >
        <h2>{{ heading }}</h2>
        <slot />
    </section>
</template>
