// public-good-design-system-react-headless/components/Textarea.tsx
// Textarea component
//
// A headless multi-line text input that wraps the native HTML <textarea>
// element. Used for comments, messages, descriptions, feedback, code input,
// and any scenario where users need to enter extended text content. Unlike
// a single-line TextInput, Textarea provides a larger, scrollable text area
// that supports multiple lines.
//
// Props:
//   className — string, optional. CSS class name.
//   label — string, required. Accessible name via aria-label.
//   value — string, default "". Bindable text content; supports value + onChange.
//   rows — number, default undefined. Number of visible text rows.
//   required — boolean, default false. Whether the textarea is required.
//   disabled — boolean, default false. Whether the textarea is disabled.
//   ...restProps — additional HTML attributes spread onto the <textarea>.
//
// Syntax:
//   <Textarea label="Comments" value={value} onChange={setValue} rows={5} />
//
// Examples:
//
//   <Textarea label="Description" value={description} onChange={setDescription} required />
//
//
//   <Textarea label="Notes" value={value} onChange={setValue} disabled={isReadOnly} />
//
// Keyboard:
//   - Tab: moves focus to and from the textarea (native behavior)
//   - Enter: inserts a new line (does not submit forms)
//   - All standard text editing keys function normally
//
// Accessibility:
//   - aria-label={label} provides an accessible name since no visible <label> is included
//
// Internationalization:
//   - The label prop accepts any translated string
//   - No hardcoded user-facing strings
//
// Claude rules:
//   - Headless: no CSS, no styles -- consumer provides all styling
//   - Uses controlled for two-way data binding on value
//   - Consumer can wrap with their own visible <label> element
//
// References:
//   - MDN textarea element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

import React from "react";

export interface TextareaProps {
    className?: string;
    /** Accessible label. */
    label: string;
    /** Current value. Bindable. */
    value?: string;
    /** Number of visible rows. */
    rows?: number;
    /** Whether required. */
    required?: boolean;
    /** Whether disabled. */
    disabled?: boolean;
    /** Callback when value changes. */
    onChange?: (value: string) => void;
    [key: string]: unknown;
}

export default function Textarea({
    className = "",
    label,
    value = "",
    rows = undefined,
    required = false,
    disabled = false,
    onChange,
    ...restProps
}: TextareaProps) {
    return (
        <textarea
        className={`textarea ${className}`}
        aria-label={label}
        value={value} onChange={(e) => onChange?.(e.target.value)}
        rows={rows}
        required={required}
        disabled={disabled}
        {...restProps}
        ></textarea>
    );
}

// public-good-design-system-vue-nuxt-examples/components/Textarea.vue
<script setup lang="ts">

    // Textarea component
    //
    // A headless multi-line text input that wraps the native HTML <textarea>
    // element. Used for comments, messages, descriptions, feedback, code input,
    // and any scenario where users need to enter extended text content. Unlike
    // a single-line TextInput, Textarea provides a larger, scrollable text area
    // that supports multiple lines.
    //
    // Props:
    //   className — string, optional. CSS class name.
    //   label — string, required. Accessible name via aria-label.
    //   value — string, default "". Bindable text content; supports v-model.
    //   rows — number, default undefined. Number of visible text rows.
    //   required — boolean, default false. Whether the textarea is required.
    //   disabled — boolean, default false. Whether the textarea is disabled.
    //   ...restProps — additional HTML attributes spread onto the <textarea>.
    //
    // Syntax:
    //   <Textarea label="Comments" v-model rows={5} />
    //
    // Examples:
    //   <!-- Required description field -->
    //   <Textarea label="Description" v-model={description} required />
    //
    //   <!-- Read-only notes -->
    //   <Textarea label="Notes" v-model disabled={isReadOnly} />
    //
    // Keyboard:
    //   - Tab: moves focus to and from the textarea (native behavior)
    //   - Enter: inserts a new line (does not submit forms)
    //   - All standard text editing keys function normally
    //
    // Accessibility:
    //   - aria-label={label} provides an accessible name since no visible <label> is included
    //
    // Internationalization:
    //   - The label prop accepts any translated string
    //   - No hardcoded user-facing strings
    //
    // Claude rules:
    //   - Headless: no CSS, no styles -- consumer provides all styling
    //   - Uses defineModel() for two-way data binding on value
    //   - Consumer can wrap with their own visible <label> element
    //
    // References:
    //   - MDN textarea element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

    withDefaults(defineProps<{
        /** Accessible label. */
        label: string;
        /** Number of visible rows. */
        rows?: number;
        /** Whether required. */
        required?: boolean;
        /** Whether disabled. */
        disabled?: boolean;
    }>(), {
        rows: undefined,
        required: false,
        disabled: false,
    });

    const modelValue = defineModel<string>({ default: "" });

</script>

<template>
    <!-- Textarea.vue -->
    <textarea
        class="textarea"
        :aria-label="label"
        v-model="modelValue"
        :rows="rows"
        :required="required"
        :disabled="disabled"
    ></textarea>
</template>
